W7D2/music_app/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  resource :session, only: [:new, :create, :destroy]

  resources :users, only: [:show, :new, :create]

  resources :bands
end

W7D2/music_app/app/models/album.rb
class Album < ApplicationRecord

    def show
        @album = Album.find(params[:id])
        render :show
    end
    
    def new
        @band = Band.find(params[:band_id])
        @album = Album.new(band_id: params[:band_id])
        render :new
    end
    
    def create
        @album = Album.new(album_params)
    
        if @album.save
          redirect_to album_url(@album)
        else
          @band = @album.band
          flash.now[:errors] = @album.errors.full_messages
          render :new
        end
    end
    
    def edit
        @album = Album.find(params[:id])
        render :edit
    end
    
    def update
        @album = Album.find(params[:id])
    
        if @album.update(album_params)
          redirect_to album_url(@album)
        else
          flash.now[:errors] = @album.errors.full_messages
          render :edit
        end
    end
    
    def destroy
        @album = Album.find(params[:id])
        @album.destroy
        redirect_to band_url(@album.band_id)
    end
    
    private
    
    def album_params
        params.require(:album).permit(:band_id, :live, :name, :year)
    end
end

W7D2/music_app/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

W7D2/music_app/app/models/band.rb
class Band < ApplicationRecord

    validates :name, presence: true
end

W7D2/music_app/app/models/user.rb
class User < ApplicationRecord

    validates :email, :session_token, uniqueness: true
    validates :password, length: { minimum: 6, allow_nil: true }
    validates :email, :password_digest, :session_token, :activation_token, presence: true

    after_initialize :ensure_session_token

    attr_reader :password

    def self.find_by_credentials(email, password)
        user = User.find_by(email: email)
        user && user.is_password?(password) ? user : nil
    end

    def password=(password)
        @password = password
        self.spassword_digest = BCrypt::Password.create(password)
    end

    def is_password?(password)
        BCrypt::Password.new(self.password_digest).is_password?(password)
    end

    def reset_session_token!
        self.session_token = SecureRandom.urlsafe_base64
        self.save!
        self.session_token
    end

    def ensure_session_token
        self.session_token ||= SecureRandom.urlsafe_base64

    end
end

W7D2/music_app/app/controllers/albums_controller.rb
class AlbumsController < ApplicationController

    def show
        @album = Album.find(params[:id])
        render :show
    end
    
    def new
        @band = Band.find(params[:band_id])
        @album = Album.new(band_id: params[:band_id])
        render :new
    end
    
    def create
        @album = Album.new(album_params)
    
        if @album.save
          redirect_to album_url(@album)
        else
          @band = @album.band
          flash.now[:errors] = @album.errors.full_messages
          render :new
        end
    end
    
    def edit
        @album = Album.find(params[:id])
        render :edit
    end
    
    def update
        @album = Album.find(params[:id])
    
        if @album.update(album_params)
          redirect_to album_url(@album)
        else
          flash.now[:errors] = @album.errors.full_messages
          render :edit
        end
    end
    
    def destroy
        @album = Album.find(params[:id])
        @album.destroy
        redirect_to band_url(@album.band_id)
    end
    
    private
    
    def album_params
        params.require(:album).permit(:band_id, :live, :name, :year)
    end
end

W7D2/music_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :current_user, :logged_in?

    def current_user
        return nil unless session[:session_token]
        @current_user ||= User.find_by(session_token: session[:session_token])
    end

    def logged_in?
        !!current_user
    end

    def log_in_user!(user)
        session[:session_token] = user.reset_session_token!
    end
end

W7D2/music_app/app/controllers/bands_controller.rb
class BandsController < ApplicationController

    def index
        @band = Band.all
        render :index
    end

    def new
        @band = Band.new
        render :new
    end

    def show
        @band = Band.find(params[:id])
        render :show
    end

    def create
        @band = Band.new(band_params)
    
        if @band.save
          redirect_to band_url(@band)
        else
          flash.now[:errors] = @band.errors.full_messages
          render :new
        end
    end


  def edit
    @band = Band.find(params[:id])
    render :edit
  end 

  def update
    @band = Band.find(params[:id])
    if @band.update(band_params)
      redirect_to band_url(@band)
    else
      flash.now[:errors] = @band.errors.full_messages
      render :edit
    end
  end

  def destroy
    @band = Band.find(params[:id])
    @band.destroy
    redirect_to bands_url
  end

  private
  
  def band_params
    params.require(:band).permit(:name)
  end
end

W7D2/music_app/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    def new
        render :new
    end

    def create
        user = User.find_by_credentials(params[:user][:email], params[:user][:password])
        if user
            log_in_user(user)
            redirect_to user_url
        else
            render json: "not credentials."
        end
    end

    def destroy
        current_user.reset_session_token!
        session[:session_token] = nil
    
        redirect_to new_session_url
    end
end

W7D2/music_app/app/controllers/users_controller.rb
class UsersController < ApplicationController

    def show
        render :show
    end

    def new
        @user = User.new
        render :new
    end

    def create
        @user = User.new(user_params)
        if @user.save
            log_in_user!(@user)
            redirect_to user_url
        else
            flash.now[:errors] = @user.errors.full_message
            render :new
        end
    end

    private

    def user_params
        params.require(:user).permit(:email, :password)
    end
end

W7D2/music_app/app/helpers/albums_helper.rb
module AlbumsHelper
end

W7D2/music_app/app/helpers/application_helper.rb
module ApplicationHelper
end

W7D2/music_app/app/helpers/bands_helper.rb
module BandsHelper
end

W7D2/music_app/app/helpers/sessions_helper.rb
module SessionsHelper
end

W7D2/music_app/app/helpers/users_helper.rb
module UsersHelper
end

W7D2/music_app/app/views/albums/edit.html.erb
<h1 class='page-header'>Edit <%= @album.name %></h1>

<%= render "form", album: @album %>

W7D2/music_app/app/views/albums/new.html.erb
<h1 class='page-header'>New <%= @band.name %> Album!</h1>

<%= render "form", album: @album %>

W7D2/music_app/app/views/bands/_form.htrml.erb
<% action_url = band.persisted? ? band_url(band) : bands_url %>
<% http_method = band.persisted? ? "PATCH" : "POST" %>

<form class='form' action="<%= action_url %>" method="POST">
  <input type="hidden" name="_method" value="<%= http_method %>">
  <input
    type="hidden"
    name="authenticity_token"
    value="<%= form_authenticity_token %>">

  <p>
    <label for='band-name'>Name</label>
    <input id='band-name' type="text" name="band[name]" value="<%= band.name %>">
  </p>

  <input type="submit">
</form>

W7D2/music_app/app/views/bands/edit.html.erb
<h1 class='page-header'>Edit <%= @band.name %></h1>

<%= render "form", band: @band %>

W7D2/music_app/app/views/bands/index.html.erb
<h1 class='page-header'>Bands</h1>

<ul class='main-list'>
  <% @bands.each do |band| %>
    <li><a href="<%= band_url(band) %>"><p><%= band.name %></p></a></li>
  <% end %>
</ul>

<h4 class='sub-header'>Links</h4>
<ul class='page-links'>
  <li><a class='button' href="<%= new_band_url %>" >New band</a></li>
</ul>

W7D2/music_app/app/views/bands/new.html.erb
<h1 class='page-header'>New Band!</h1>

<%= render "form", band: @band %>

W7D2/music_app/app/views/bands/show.html.erb
<h1 class='page-header'><%= @band.name %></h1>

<h4 class='sub-header'>Albums</h4>

<% if @band.albums.length > 0 %>
  <ul class='main-list'>
  <% @band.albums.each do |album| %>
    <li><a href="<%= album_url(album) %>"><p><%= album.name %></p></a></li>
  <% end %>
  </ul>
<% else %>
  <p>This band has no albums... yet!</p>
<% end %>

<h4 class='sub-header'>Links</h4>
<ul class='page-links'>
  <li><a class='button' href="<%= new_band_album_url(@band) %>">New album</a></li>
  <li><a class='button' href="<%= edit_band_url(@band) %>">Edit Band</a></li>
  <li>
    <form action="<%= band_url(@band) %>" method="POST">
      <input type="hidden" name="_method" value="DELETE">
      <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>" >
      <input type="submit" value="Destroy Band">
    </form>
  </li>
  <li><a class='button' href="<%= bands_url %>">All bands</a></li>
</ul>

W7D2/music_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MusicApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <h1 class="main-logo">Music App</h1>
      <% if logged_in? %>
        <nav>
          <a class='button' href="<%= bands_url %>">Take me Home</a>
          
          <div class='user-detail'>
            <p>Logged in as: <%= current_user.email %></p>
          <form action=<%= session_url %> method='post'>
            <input type="hidden" name="_method" value="delete">
            <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
            <input type="submit" value="Sign Out">
          </form>
          </div>
        </nav>

    <%= yield %>
  </body>
</html>

W7D2/music_app/app/views/users/new.html.erb
<h1 class='page-header'>New User</h1>

<a class='button' href=<%= new_session_url %> >Go to sign-in</a>

<form class='form' action="<%= users_url %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

  <p>
    <label >Email</label>
    <input type="text" name="user[email]">
  </p>

  <p>
    <label >Password</label>
    <input type="password" name="user[password]">
  </p>

  <input type="submit" value="Submit">
</form>

W7D2/music_app/app/views/users/show.html.erb
<h1 class='page-header'>User Profile</h1>
<p>
  Email: <%= current_user.email %>
</p>